[package]
name = "random-class"
version = "1.0.1"
description = "Class to easily instantiate random number generator objects."
repository = "https://github.com/ArielRobotti/RandomClass"
keywords = [
  "Random",
  "RandomArray",
  "Rand",
  "RandClass",
  "RandRange",
  "RandPrincipal"
]
license = "MIT"

[dependencies]
base = "0.10.0"