[package]
name = "random-class"
version = "2.0.0"
description = "Class to easily instantiate random number generator objects."
repository = "https://github.com/ArielRobotti/RandomClass"
keywords = [
  "Random",
  "RandomArray",
  "Rand",
  "RandClass",
  "RandRange",
  "RandPrincipal"
]
license = "MIT"